const fs = require('fs');
const path = require('path');
require('dotenv').config({ path: path.resolve(__dirname, '../.env.local') });

const envDir = path.resolve(__dirname, '../src/environments');

// Asegurar que el directorio existe
if (!fs.existsSync(envDir)) {
  fs.mkdirSync(envDir, { recursive: true });
}

// Obtener variables de entorno con valores por defecto
// Nota: dotenv convierte guiones a guiones bajos, pero también podemos leer directamente
const apiUrl = process.env['API-URL'] || process.env.API_URL || 'http://localhost:1338';
const strapiKey = process.env['STRAPI-KEY'] || process.env.STRAPI_KEY || '';

// Generar environment.ts (desarrollo)
const environmentDev = `// This file is auto-generated by scripts/generate-env.js
// DO NOT EDIT MANUALLY - Your changes will be overwritten
// Edit .env.local instead

export const environment = {
  production: false,
  apiUrl: '${apiUrl}',
  strapiKey: '${strapiKey}'
};
`;

// Generar environment.prod.ts (producción)
const environmentProd = `// This file is auto-generated by scripts/generate-env.js
// DO NOT EDIT MANUALLY - Your changes will be overwritten
// Edit .env.local instead

export const environment = {
  production: true,
  apiUrl: '${apiUrl}',
  strapiKey: '${strapiKey}'
};
`;

// Escribir los archivos
fs.writeFileSync(path.join(envDir, 'environment.ts'), environmentDev, 'utf8');
fs.writeFileSync(path.join(envDir, 'environment.prod.ts'), environmentProd, 'utf8');

console.log('✅ Archivos environment generados desde .env.local');
console.log(`   API_URL: ${apiUrl}`);
console.log(`   STRAPI_KEY: ${strapiKey ? '***' + strapiKey.slice(-4) : '(vacío)'}`);

